### ISSUE TITLE
on resize, we lost the left menu completely which will be a problem for tablets

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRSS#18]
![image](https://user-images.githubusercontent.com/3675043/41351346-1064cefc-6ee4-11e8-8c83-563627497dec.png)

**Comment by b-solution** [comment]
it's the smart admin that hide it, i had to put the header to be able to toggle to menu

**Comment by bluenevus** [comment]
Ohhhh, well before we put it back…let me simply test it out on the ipads because the screen area is where we want it now

Also, at certain screen resolutions, I can’t close the left menu

[cid:image001.png@01D402F8.19FBBBE0]

--- vr, Frank

**Comment by bluenevus** [comment]
![cant close](https://user-images.githubusercontent.com/3675043/41353919-9cf3c286-6eeb-11e8-8444-79bb7a509d50.png)

at this resolution, the left menu bar doesn't close at all.  Clicking the button to close it just causes it to pop back open
