### ISSUE TITLE
the time and date dialog must always pop above the field and not below

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRSS#22]
sometimes it pops below the field and when it does that, it gets cutoff and you cant get out of it without refreshing so the date and time popups must go in this direction all the time please

![image](https://user-images.githubusercontent.com/3675043/41981887-03acb0d4-79f8-11e8-8806-46c7690a9371.png)

**Comment by bluenevus** [comment]
can we prevent it from doing this? going down.  it should always go up like the pic above NOT like below?
![microsoftteams-image](https://user-images.githubusercontent.com/3675043/41997672-acd21842-7a26-11e8-8f23-0584ea12ae07.png)

**Comment by b-solution** [comment]
this seems to be an issue with all users, i've added a way to scroll and be able to see the widget
