### ISSUE TITLE
Create Admin Screen to input/edit administrative features and to configure settings

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRSS#35]
ADMIN SCREEN

(top section)
New Room button; when clicked will display New Room modal
Rooms table (displays existing rooms)
(for each) room name     edit icon    delete icon
click edit icon will display Edit Room modal
click delete icon will confirm delete
 
(middle section)
New User button; when clicked will display New User modal
Users table (displays existing users)
(for each) user name     edit icon    delete icon
click edit icon will display Edit User modal
click delete icon will confirm delete
 
(bottom section)
Settings
(displays present content on https://mrss.microhealthllc.com/settings)

**Comment by bluenevus** [comment]
there is no way to edit a room on the room screen only add.  there is also no way to delete a room on the screen

**Comment by b-solution** [comment]
If you are connected so any user can edit/Delete room
