### ISSUE TITLE
Keyboard gets in the way when trying to edit start time and end time on ipad

### ISSUE THREAD

**Issue by lyfelee** [MicroHealthLLC/mRSS#39]
![mrss ipad issue](https://user-images.githubusercontent.com/29629102/50306029-7bb0c800-0462-11e9-8d80-c7adb0467862.jpg)

**Comment by LAlexMHllc** [comment]
Try making the Time Start and Time End input textboxes "readonly" and include a button next to each with the function to display the datetimepicker onclick.
