### ISSUE TITLE
clicking on one of the available times for a meeting doesn't launch the meeting dialog

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRSS#4]
![image](https://user-images.githubusercontent.com/3675043/41304285-bdb31b6a-6e3d-11e8-90b0-fa159cff5f7f.png)

**Comment by bluenevus** [comment]
clicking the day should automatically fill in the date, start time and end time base on the area they clicked

![image](https://user-images.githubusercontent.com/3675043/41304342-da7b22ba-6e3d-11e8-918c-4ff19dc9025b.png)

**Comment by b-solution** [comment]
fixed the second picture
when we click on a meeting we go to show page

**Comment by bluenevus** [comment]
you know when you click on a time in google calendar, it will launch the dialog with the time and day you selected and enter those values?  That is what I'm looking for so people can just touch the area to the date, time start and time end will be in the block they will make the appointment like google calendar

**Comment by bluenevus** [comment]
also, in the 2nd picture if I click a new meeting the date should default to the day chosen in the calendar since I'm on that day anyway
