### ISSUE TITLE
cant start it on nginx

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRSS#5]
![image](https://user-images.githubusercontent.com/3675043/41306207-5bc546fc-6e43-11e8-8d1c-b8a68192801b.png)

**Comment by bluenevus** [comment]
can't start it as a background process either
![image](https://user-images.githubusercontent.com/3675043/41306813-547360da-6e45-11e8-8b58-a4015d71d6ea.png)

**Comment by bluenevus** [comment]
rails s -e development -b 0.0.0.0 -p 80 -d

**Comment by b-solution** [comment]
https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers

**Comment by bluenevus** [comment]
![image](https://user-images.githubusercontent.com/3675043/41311562-9b1cef6c-6e52-11e8-8c4a-5fc6c237b5fa.png)

**Comment by bluenevus** [comment]
cant get it running in production mode
