### ISSUE TITLE
Admin - Rooms screen - Include Edit and Delete icons for each room on Rooms table.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRSS#58]

**Comment by bluenevus** [comment]
Frank Tucker
there is no way to edit a room on the room screen only add.  there is also no way to delete a room on the screen

**Comment by LAlexMHllc** [comment]
Screenshot Example

![rooms_screen_include_edit_delete_icons](https://user-images.githubusercontent.com/11938477/52361734-e7e48c80-2a0c-11e9-8737-277529754ca3.jpg)
