### ISSUE TITLE
unable to enter time because keyboard blocks the time control.

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRSS#59]
unable to enter time because keyboard blocks the time control.  I think you need to use a different time control where there is no data entry so the keyboard never pops up

![20190206_092112](https://user-images.githubusercontent.com/3675043/52355939-4c015380-2a01-11e9-8e9a-e7c3c1b4f671.jpg)

**Comment by bluenevus** [comment]
I tried rotating the pad, I tried clicking the keyboard to go away but it loses focus on the time control  when I click the time control again, keyboard pops back up blocking time

**Comment by LAlexMHllc** [comment]
Try making the Time Start and Time End input textboxes "readonly" and include a button next to each with the function to display the datetimepicker onclick.
